server:
  port: @api-server-port@
  tomcat:
    uri-encoding: UTF-8
    http:
      encoding:
        force: true
        charset: UTF-8
        enabled: true
    max-threads: 1000
    min-spare-threads: 30
    connection-timeout: 5000ms
    servlet:
      context-path: /

spring:
  application:
    name: happy-live-api
  profiles:
    active: @package.environment@
  devtools:
    livereload:
      port: @api-devtools-livereload-port@
  info: #定义各种额外的详情给服务端显示
    app:
      name: "@project.name@" #从pom.xml中获取
      description: "@project.description@"
      version: "@project.version@"
      spring-boot-version: "@project.parent.version@"

logging:
  config: classpath:logback.xml



#微信相关配置
weixin:
  miniAppID: wxe4376ab3f40080b1
  miniAppSecret: c00c14549a270296894b86792a49a87d